<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260408111851 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0 ON messenger_messages (queue_name)');
        $this->addSql('CREATE INDEX IDX_75EA56E0E3BD61CE ON messenger_messages (available_at)');
        $this->addSql('CREATE INDEX IDX_75EA56E016BA31DB ON messenger_messages (delivered_at)');
        $this->addSql('DROP INDEX idx_banner_active_dates');
        $this->addSql('ALTER TABLE banner ALTER id TYPE VARCHAR(36)');
        $this->addSql('ALTER TABLE banner ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE banner ALTER active DROP DEFAULT');
        $this->addSql('ALTER TABLE banner ALTER background_color DROP DEFAULT');
        $this->addSql('ALTER TABLE banner ALTER content TYPE JSON');
        $this->addSql('ALTER TABLE banner ALTER created_at DROP DEFAULT');
        $this->addSql('ALTER TABLE banner ALTER created_at SET NOT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE messenger_messages');
        $this->addSql('ALTER TABLE banner ALTER id TYPE UUID');
        $this->addSql('ALTER TABLE banner ALTER id SET DEFAULT \'gen_random_uuid()\'');
        $this->addSql('ALTER TABLE banner ALTER active SET DEFAULT false');
        $this->addSql('ALTER TABLE banner ALTER background_color SET DEFAULT \'#FFFFFF\'');
        $this->addSql('ALTER TABLE banner ALTER content TYPE JSONB');
        $this->addSql('ALTER TABLE banner ALTER created_at SET DEFAULT \'now()\'');
        $this->addSql('ALTER TABLE banner ALTER created_at DROP NOT NULL');
        $this->addSql('CREATE INDEX idx_banner_active_dates ON banner (active, start_date, end_date)');
    }
}
